server.port=8080

# C?u hình k?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/srpm_db
spring.datasource.username=postgres
spring.datasource.password=123456 

# C?u hình JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true